sudo: required
services:
- docker
os:
- linux
env:
  global:
  - DOCKER_IMAGE_NAME="gudang_workout"
  - DOCKER_HUB_ORG="bimonalta"
before_install:
- openssl aes-256-cbc -K $encrypted_7c0c0d63417d_key -iv $encrypted_7c0c0d63417d_iv -in deploy.rsa.enc -out deploy.rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy.rsa
- ssh-add deploy.rsa
- docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
script:
- sudo chmod +x deploy.sh
- sudo chmod 600 deploy.rsa
after_script:
- docker build -t ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:backend-${TRAVIS_BUILD_ID} .
- docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:backend-${TRAVIS_BUILD_ID}
- docker tag ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:backend-${TRAVIS_BUILD_ID} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:be2
- docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:be2
- ssh-keyscan -H $SSH_IP >> ~/.ssh/known_hosts
- ssh -v -i deploy.rsa $SSH_USER@$SSH_IP DIR=$ROOT_DIR  'bash -s' < deploy.sh


